---
kind: pipeline
type: docker
name: vinlottis

platform:
  os: linux
  arch: amd64

steps:
- name: frontend_install
  image: node:13.6.0
  commands:
    - node -v
    - yarn --version¨
    - yarn
- name: deploy
  image: appleboy/drone-ssh
  pull: true
  secrets:
    - ssh_key
  when:
    event:
      - push
    branch:
      - master
      - drone-test
    status: success
  settings:
    host: 10.0.0.114
    username: root
    key:
      from_secret: ssh_key
    command_timeout: 600s
    script:
      - /home/kevin/deploy/vinlottis.sh

trigger:
  branch:
    - master
  event:
    include:
      - pull_request
      - push 
